version: '3.9'

services:
  db:
    image: postgres:16
    restart: always
    shm_size: 128mb
    env_file:
      - "movies_admin/config/.env"
    volumes:
      - postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgresql: